added dal, business-logic
microservices-course-itmo/winestyle-parser-service pull request #1
Opened 2020-09-30 07:36 UTC by Gashad0kuro

added a single table "wines" + entity class and a controller to test functionality of repository and business-logic

2020-10-01 08:58 UTC, InRedikaWB requested changes
Руты бы переделать под рест. Кажется, на лекциях еще не рассказывали, тогда стоит собрать эту инфу и возможно зашарить между лидами.

2020-10-01 08:58 UTC, InRedikaWB commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/TestWineController.java
> +    @GetMapping("/all")
Не по REST-у немного)
Емнип, бест практис роутинга - это дефолтный круд:
GET /api/my-entity-name - get all
GET /api/my-entity-name/{id} - get by id
POST /api/my-entity-name - add new

2020-10-01 08:58 UTC, InRedikaWB commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/TestWineController.java
> +            @RequestParam Float strength, @RequestParam String sugar, @RequestParam Float volume) {
Дто и через тело запроса? У get'а не лимит есть длинны, когда-то выстрелит)

2020-10-01 08:58 UTC, InRedikaWB commented on src/main/java/com/wine/to/up/winestyle/parser/service/domain/entity/Wine.java
> +
meh

2020-10-01 08:58 UTC, InRedikaWB commented on src/main/java/com/wine/to/up/winestyle/parser/service/services/WineService.java
> +import lombok.RequiredArgsConstructor;
А по какому принципу тут отступы делаются? Во всех файлах выше еще просматривалась логика,.

2020-10-04 12:00 UTC, shinehlina requested changes

2020-10-04 12:00 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/MessageController.java
> +//import lombok.extern.slf4j.Slf4j;
?

2020-10-04 12:00 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/TestWineController.java
> +//import com.wine.to.up.winestyle.parser.service.repository.WineRepository;
?

2020-10-04 12:00 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/services/WineService.java
> +import lombok.RequiredArgsConstructor;
Согласна)

2020-10-04 12:00 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/services/WineService.java
> +
Тут какая-то вообще с отступами интересная история

2020-10-04 12:00 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/services/WineService.java
> +    public void addNew(String brand, String color, String grape, String name, Integer price, String region,
Это реально выглядит длинновато

2020-10-17 10:30 UTC, closed without merging