Sprint 6
microservices-course-itmo/winestyle-parser-service pull request #11
Opened 2020-11-06 19:10 UTC by baby-benz

1. Добавлена поддержка прокси.
2. Исправлен таймер количества распаршенных сущностей в секунду.
3. Переписан cтатус-сервис для небольшого увеличения производительности.
4. Теперь шедулер находится в отдельном компоненте и вместо запуска в отдельном потоке в случае, если процесс парсинга уже идет, ожидает окончания.
5. Исправлена передача CSV-файла и ее эндпоинт.
6. Добавлена поддержка многопоточности. Взятие HTML-документа и парсинг отдельного продукта теперь происходят в самостоятельных потоках.
7. Логи об отсутсвии некоторых свойств теперь сопровождаются ссылками на этот продукт, т.к. логи разных продуктов идут вперемешку из-за внедрения многопоточности.
8. Добавлен пул объектов сервиса забора HTML-документов, т.к. разные потоки теперь конфликтуют за этот ресурс, а блокировка этого ресурса отрицательно сказывается на производительности. Вместо этого каждому потоку, которому необходим забор документов, предоставляется свой собственный экземпляр сервиса.
9. И другие множественные фиксы.

2020-11-07 15:55 UTC, AfanasievYuriy requested changes

2020-11-07 15:55 UTC, AfanasievYuriy commented on pom.xml
> +		</dependency>
форматирование съехало

2020-11-07 15:55 UTC, AfanasievYuriy commented on pom.xml
> +            <version>2.8.6</version>
версию в проперти

2020-11-07 15:55 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/MainController.java
> +                } catch (IllegalArgumentException | IllegalAccessException ignore) {
ребят, если уж catch блок есть, то добавьте туда какое-то поведение (минимум - лог, а желательно какой-то осознанный ответ клиенту)

2020-11-07 15:55 UTC, AfanasievYuriy commented on pom.xml
> +        <service.commonlib.version>0.2.2-SNAPSHOT</service.commonlib.version>
обновитесь до последней версии

2020-11-07 15:55 UTC, AfanasievYuriy commented on pom.xml
>          <parser.common.api.version>0.2.1-SNAPSHOT</parser.common.api.version>
обновитесь до последней версии

2020-11-07 18:39 UTC, baby-benz commented on pom.xml
>          <parser.common.api.version>0.2.1-SNAPSHOT</parser.common.api.version>
Но ведь это актуальные версии

2020-11-07 19:17 UTC, kav128 commented on pom.xml
> +        <service.commonlib.version>0.2.2-SNAPSHOT</service.commonlib.version>
0.2.2-SNAPSHOT - и есть последняя версия для service-common-lib

2020-11-09 10:47 UTC, Kanootoko commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/MainController.java
> +                } catch (IllegalArgumentException | IllegalAccessException ignore) {
Блок есть, но он в принципе не может сработать, поэтому из него и убрано любое поведение. Мы бежим циклом по полям, делаем их доступными, и обращаемся. IllegalArgumentException невозможен, так как поле взято из списка полей, а IllegalAccessException невозможен, раз мы дали доступ

2020-11-10 15:14 UTC, shinehlina requested changes
Ой, кажется, я не засабмитила

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/exception/GlobalExceptionHandler.java
> +        if (ex instanceof IllegalFieldException) {
Так не стоит делать, просто отдельный метод @ExceptionHandler(IllegalFieldException.class)

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ProxyService.java
> +            URL url = new URL("https://api.proxyscrape.com/?request=getproxies&proxytype=socks5&country=all");
Надо куда-то это вынести. Наример, в проперти

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ProxyService.java
> +            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
try with resources

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ProxyService.java
> +            Jsoup.connect("https://winestyle.ru/").proxy(proxy).timeout(maxTimeout).get();
Ссылку на сайт тоже лучше не так, вы же не в одном месте это используете

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ProxyService.java
> +    private IUnstableLoader getProxyIfAlive(String proxyAddress, int maxTimeout) {
Мне не очень нравится) Может, getAliveProxy было бы лучше?

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ProxyService.java
> +            return null;
Null не очень хорошо возвращать. Можно попробовать optional

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ProxyService.java
> +        futures = proxyAddresses.stream().map(proxyAddress -> CompletableFuture.supplyAsync(() -> getProxyIfAlive(proxyAddress, maxTimeout), threadPool)).collect(Collectors.toList());
Можно отдельно не объявлять)

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ScrapingService.java
> +                e.printStackTrace();
Логгер)

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ScrapingService.java
> +        if (timeout > 0) Thread.sleep(timeout);
Нехорошо в одной строчке

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/SimpleWebPageLoader.java
> +        return "SimpleWebPageLoader{}";
Это зачем?)

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +    @SneakyThrows
Нехорошо, не используйте лучше

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +    @SneakyThrows
И здесь

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +    @SneakyThrows
зд

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/scheduling/AlcoholParsingScheduler.java
> +    @SneakyThrows(UnsupportedAlcoholTypeException.class)
з

2020-11-10 15:14 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/scheduling/AlcoholParsingScheduler.java
> +    @SneakyThrows(UnsupportedAlcoholTypeException.class)
з

2020-11-10 15:14 UTC, shinehlina commented on src/test/java/com/wine/to/up/winestyle/parser/service/TestingWebApplicationTest.java
> +@ComponentScan("com.wine.to.up")
Без этого не работает?

2020-11-10 15:14 UTC, shinehlina commented on src/test/java/com/wine/to/up/winestyle/parser/service/TestingWebApplicationTest.java
> +	// public void alcoholByURLSuccess() throws Exception {
Закомментированный?

2020-11-10 15:14 UTC, shinehlina commented on src/test/resources/application.properties
> +spring.datasource.username=postgres
Вы собираетесь тестировать на реальной базе?

2020-11-10 15:14 UTC, shinehlina commented on src/test/resources/application.properties
> +scheduler.cron.expression=0 0 0 * * *
И со скедулингом?

2020-11-10 15:14 UTC, shinehlina commented on src/test/resources/application.properties
> +spring.flyway.baseline-on-migrate=true
И с миграцией?

2020-11-10 15:14 UTC, shinehlina commented on src/test/resources/application.properties
> +management.endpoints.web.exposure.include=prometheus
И с промитиусом? Вставьте только нужные

2020-11-25 09:23 UTC, baby-benz commented on src/test/java/com/wine/to/up/winestyle/parser/service/TestingWebApplicationTest.java
> +@ComponentScan("com.wine.to.up")
Нет, без этого не подтянет ParserCommonApiProperties и ParserApi, потому что они находятся в com.wine.to.up.parser, а проект в com.wine.to.up.winestyle

2021-03-03 15:31 UTC, Kanootoko commented
Sprint-12 is already merged to `dev`, so I'm closing this pull request

2021-03-03 15:31 UTC, closed without merging