embed parser application codebase in winestyle-parser-service
microservices-course-itmo/winestyle-parser-service pull request #2
Opened 2020-10-02 22:01 UTC by baby-benz

Parser services have been implemented. Communication with the database occurs through the business logic layer. The design of interfaces based on REST Api principles has begun. A generic controller exception handler has been added.

2020-10-04 11:57 UTC, shinehlina requested changes
Только очень минорные штуки)

2020-10-04 11:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/ParseController.java
> +    @ResponseStatus(HttpStatus.OK)
Вы же и так внизу возвращаете "ok". Зачем это?

2020-10-04 11:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/ParseController.java
> +    @RequestMapping(value = "{alcohol}", method = RequestMethod.POST)
Вы, кстати,  можете заюзать @PostMapping аннотацию, она более новая

2020-10-04 11:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/ParserService.java
> +    @Scheduled(cron = "0 0 0 * * *") // second, minute, hour, day of month, month, day(s) of week(0-6)
Вынесите лучше в проперти

2020-10-04 11:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/WineService.java
> +        } else
Лучше все-таки юзать скобки. Вы в ифе на одну строчку это делаете, а так странно выглядит

2020-10-04 11:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/DocumentService.java
> +        Thread.sleep(600);
Это зачем?

2020-10-04 12:05 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/DocumentService.java
> +        Thread.sleep(600);
Это временное решение, чтобы избежать IP-блокинга за слишком большое количество запросов

2020-10-07 19:42 UTC, shinehlina requested changes
В целом мне понравилось)

2020-10-07 19:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/MainController.java
> +    public ResponseEntity<Map<String, Object>> getParsedWineWithFields(@PathVariable long id,
Напишите здесь javadoc, что это за fields такие

2020-10-07 19:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/MainController.java
> +    public ResponseEntity<Map<String, Object>> getParsedWineWithFields(@PathVariable long id,
Потому что сейчас я не очень понимаю, зачем это)

2020-10-07 19:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/exception/GlobalExceptionHandler.java
> +
Пробел

2020-10-07 19:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/domain/entity/Wine.java
> +        return url + " "
`@ToString`

2020-10-07 19:42 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/WineService.java
> +            return null;
В целом не очень хорошая практика null возвращать. Лучше либо Optional, либо бросать исключение. Можете поправить.

2020-10-07 19:42 UTC, shinehlina commented on src/main/resources/application.properties
> +cron.expression=0 0 0 * * *
Это как расшифровывается? Напишите сверху

2020-10-17 18:43 UTC, shinehlina requested changes

2020-10-17 18:43 UTC, shinehlina commented on pom.xml
> +            <version>1.13.1</version>
Давайте все версии в проперти

2020-10-17 18:43 UTC, shinehlina commented on pom.xml
> +        <!-- Recommended -->
Апните еще версию

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/KafkaController.java
> +@RequestMapping("/winestyle/kafka")
Можете удалить этот контроллер вообще

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/MainController.java
> +     * @throws NoEntityException если искомое вино не найдено.
Отформатируйте alt ctrl L

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/MessageController.java
>  public class MessageController {
Этот тоже можете удалить, раз уже написали свой

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler({ServiceIsBusyException.class, NoEntityException.class})
Почему вы вам не сделать хендлер отдельно для ServiceIsBusyException, отдельно для NoEntityException и просто для Exception. Такая проверка не нужна, если есть рекомендуемый способ ` if (ex instanceof ServiceIsBusyException) {`

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/exception/GlobalExceptionHandler.java
> +    protected ResponseEntity<ApiError> handleNoEntityException(NoEntityException ex,
protected?

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/exception/ServiceIsBusyException.java
> +/**Класс  ошибка, который кидается
ctrl alt L на весь проект)

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/domain/entity/Message.java
> +}
Зачем вам этот класс уже, если у вас уже свои энтити

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/logging/WinestyleParserServiceNotableEvents.java
> + * Перечисление шаблонов сообщений в/от Kafka
Ну это не совсем так. Это метрики в Промитиус будут потом

2020-10-17 18:43 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/WinestyleParserService.java
> +        for (int i = 2; i <= pages; i++) {
Почему 2?

2020-10-17 18:43 UTC, shinehlina commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
Давайте лучше через миграции создавать, как Андрей показывал. И тогда это validate

2020-10-24 22:09 UTC, shinehlina requested changes
только по возможности не пуште в pr ничего нового. Пусть pr за спринт все-таки будет

2020-10-24 22:09 UTC, shinehlina commented on pom.xml
> +        <current-version>0.5.0</current-version>
Мы пока считаем, что версии только в деве, так что это тогла 0.2.0

2020-10-24 22:09 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/ServiceApplication.java
> +@ComponentScan({"com.wine.to.up", "com.wine.to.up.winestyle.parser.service.service"})
com.wine.to.up включает в себя com.wine.to.up.winestyle.parser.service.service

2020-10-24 22:09 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/ServiceApplication.java
> +@EnableJpaRepositories("com.wine.to.up.winestyle.parser.service.repository")
Это тоже, кажеься, лишнее

2020-10-24 22:09 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/ServiceApplication.java
> +@EntityScan("com.wine.to.up.winestyle.parser.service.domain")
Бещ этого не работает?

2020-10-24 22:09 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/DocumentService.java
> +            return null;
null возвращаете

2020-10-24 22:09 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/DocumentService.java
> +            return 1;
Залогируйте, почему эта ошибка может быть. И почему вообще 1 возвращаете, а не 0?

2020-10-24 22:09 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/ScrapingService.java
> +                e.printStackTrace();
Логгер

2020-10-25 06:54 UTC, Kanootoko commented on pom.xml
> +        <current-version>0.5.0</current-version>
> Мы пока считаем, что версии только в деве, так что это тогда 0.2.0
>
Ну, мне кажется, что у нас должен быть релиз какой-то после каждого спринта, и чтобы было удобнее понимать, какая версия была когда готова, нужно использовать наименование "номер версии = номер спринта". Это был пятый спринт. Ну, подумаешь, в деве скипнутся 0.2.0-0.4.0, зато дальше будет проще

2020-10-25 20:59 UTC, shinehlina commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/DocumentService.java
> +            return 1;
Все равно неочевидно, но ок

2020-10-25 21:55 UTC, shinehlina approved these changes

2020-10-26 13:06 UTC, merged