Sprint 14 kafka endpoint
microservices-course-itmo/winestyle-parser-service pull request #30
Opened 2021-03-09 10:26 UTC by NShmendyuk

Добавлены эндпоинты для отправки датасета вин из базы данных в kafka

2021-03-10 16:57 UTC, baby-benz requested changes
Эхх задокументить бы еще все это дело

2021-03-10 16:57 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/controller/KafkaController.java
> +    public void sendAllAlcoholsToKafka() {
alcoholS

2021-03-10 16:57 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/kafka/KafkaSenderService.java
> +            .setNameFormat("Kafka-Sender_All-Alcohols-%d")
Название умещается? Там, насколько помню, есть лимит на длину name. К тому же имя явно можно укоротить

2021-03-10 16:57 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/kafka/KafkaSenderService.java
> +            log.warn("Sending wines process to kafka were interrupted!");
were?

2021-03-10 23:22 UTC, NShmendyuk commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/kafka/KafkaSenderService.java
> +            .setNameFormat("Kafka-Sender_All-Alcohols-%d")
Да, я это изменил в sprint-15-unit-test ветке
Заменю здесь на Kafka-Sender-%d

2021-03-16 22:30 UTC, baby-benz requested changes

2021-03-16 22:30 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/kafka/KafkaSenderService.java
> +            log.warn("The process of sending alcohols to kafka was interrupted!");
Так почему alcoholS? Это слово в plural пишется так же, как и в singular form

2021-03-16 22:41 UTC, NShmendyuk commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/kafka/KafkaSenderService.java
> +            log.warn("The process of sending alcohols to kafka was interrupted!");
ок ок ок, верю english уровню C1 больше, чем себе (；⌣̀_⌣́)
Исправил как надо

2021-03-16 22:43 UTC, baby-benz commented
Мест с S было больше (в логах логгера, например), но ладно, не бей, аппрувлю

2021-03-16 22:43 UTC, merged