Sprint 15 24h parsing
microservices-course-itmo/winestyle-parser-service pull request #32
Opened 2021-03-10 19:41 UTC by kav128

2021-03-10 23:14 UTC, NShmendyuk commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/scheduling/AlcoholParsingScheduler.java
> +    //@Scheduled(fixedRateString = "${spring.task.scheduling.rate.proxy.fixed.millis}")
Просто отключил загрузку прокси? Или сервис не будет блокироваться сайтом с распределенной нагрузкой?

2021-03-10 23:14 UTC, NShmendyuk commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/LoaderService.java
> +    }
А зачем отдельный статик класс геттер для SimpleWebPageLoader?

2021-03-10 23:14 UTC, NShmendyuk commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/SimpleWebPageLoader.java
>                  .get();
userAgent?

2021-03-10 23:14 UTC, NShmendyuk commented on src/main/resources/application.properties
>  spring.task.execution.pool.size=350
Может стоит уменьшить thread pool size?

2021-03-10 23:24 UTC, NShmendyuk commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/LoaderService.java
> +    }
Объяснение получил, ок

2021-03-11 14:47 UTC, baby-benz requested changes
Я бы посоветовал посмотреть на код до добавления многопоточки. Так проще, как мне кажется, чем стараться убрать ее, при этом оставляя явные следы, напоминающие о ее давнем существовании.

2021-03-11 14:47 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/SimpleWebPageLoader.java
>                  .get();
А куда ушел userAgent?

2021-03-11 14:47 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +                    Integer currentUnparsed = new MainJob(currentDoc, start, scraper).call();
В данном случае, если не ошибаюсь, callable будет работать как обычная функция в основном потоке. Зачем лишняя обертка?

2021-03-11 14:47 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +            List<Pair<ProductJob, String>> parsingFutures = new ArrayList<>();
Формально это больше не futures

2021-03-11 14:47 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +                parsingFutures.add(new Pair<>(productJob, productUrl));
В чем вообще смысл этой коллекции, если работа выполняется в одном потоке? Вместо цикла на запуск парсинга в потоках (изначальный смысл, сейчас же не вижу смысла в этом цикле), можно было бы сразу запускать парсинг и обойтись без нижнего цикла. А то получается тут мы просто из одной коллекции элементов пихаем в другую коллекцию джобы, что в одном потоке не имеет никакого смысла

2021-03-11 14:47 UTC, baby-benz commented on src/main/resources/application.properties
> +spring.jsoup.scraping.timeout.millis=5000
Серьезное заявление. А почему допустимый таймаут соединения заменен на другой таймаут, совершенно иной по смыслу?

2021-03-11 14:47 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/scheduling/AlcoholParsingScheduler.java
> +    //@Scheduled(fixedRateString = "${spring.task.scheduling.rate.proxy.fixed.millis}")
@NShmendyuk не, прокси загружаются при запуске в любом случае. Тут же они еще и по времени обновлялись. Думаю, что в этом реально смысла нет, когда-то казалось логичным

2021-03-11 14:49 UTC, baby-benz commented on src/main/resources/application.properties
>  spring.task.execution.pool.size=350
Правильнее было бы "может стоит убрать эту (и еще несколько) пропертей?" Все равно больше не используются

2021-03-13 14:53 UTC, kav128 commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +            List<Pair<ProductJob, String>> parsingFutures = new ArrayList<>();
Да, забыл переименовать

2021-03-13 14:54 UTC, kav128 commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/scheduling/AlcoholParsingScheduler.java
> +    //@Scheduled(fixedRateString = "${spring.task.scheduling.rate.proxy.fixed.millis}")
Нет, здесь смысл в том, чтобы они не загружались при запуске

2021-03-13 14:55 UTC, kav128 commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
> +                parsingFutures.add(new Pair<>(productJob, productUrl));
Здесь я пытался сперва достичь цели с минимальным изменением структуры кода

2021-03-13 14:57 UTC, kav128 commented on src/main/resources/application.properties
> +spring.jsoup.scraping.timeout.millis=5000
Таймаут прокси больше не нужен, потому что прокси не используются, а таймаут загрузки (возможно, стоит переименовать в interval, лучше подходит) - для более равномерной загрузки с сайта

2021-03-13 15:01 UTC, kav128 commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/document/SimpleWebPageLoader.java
>                  .get();
Пока убрал, потому как выбрасывалась NRE в этой строчке

2021-03-16 21:18 UTC, NShmendyuk approved these changes

2021-03-16 22:33 UTC, baby-benz commented on src/main/java/com/wine/to/up/winestyle/parser/service/service/implementation/parser/ParserService.java
>                  } catch (Exception e) {
По-прежнему два цикла в том месте, где можно обойтись одним. В следующем спринте надо не забыть исправить

2021-03-16 22:33 UTC, baby-benz approved these changes

2021-03-17 11:55 UTC, merged